import shutil
import json
import string
from pathlib import Path
from .gitutils import git_clone

SWAT_LIB_DIRNAME = "lib"
SWAT_PLUGINS_DIRNAME = "plugins"

TEMPLATES = {
    "index.html": string.Template("""<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>$title</title>
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <link rel="stylesheet" href="/$libdir/swat-ui.css">
</head>
<body class="container">
  <div id="root"></div>
  <script type="module" src="./$name.js"></script>
</body>
</html>
"""),
    "page.js": string.Template("""// $name.js - simple SWAT entry module
export default async function swatApp(swat){
  const root = document.getElementById('root');
  const div = document.createElement('div');
  div.className = 'card';
  div.innerHTML = '<h3>$title</h3><p class="muted">Starter page.</p>';
  root.appendChild(div);
}
"""),
    "page.css": string.Template("/* $name.css - page styles (optional) */\n")
}

def ensure_dir(path: Path):
    path.mkdir(parents=True, exist_ok=True)

def write_file(path: Path, text: str, overwrite: bool = False):
    if path.exists() and not overwrite:
        raise FileExistsError(f"File already exists: {path}")
    ensure_dir(path.parent)
    path.write_text(text, encoding="utf-8")

def safe_copytree(src: Path, dst: Path, overwrite: bool = False):
    if not src.exists():
        raise FileNotFoundError(f"Source not found: {src}")
    if dst.exists():
        if not overwrite:
            raise FileExistsError(f"Destination exists: {dst}")
        if dst.is_dir():
            shutil.rmtree(dst)
        else:
            dst.unlink()
    shutil.copytree(src, dst)

def create_project(path: Path, name: str, swat_repo: str, version: str | None = None):
    path = Path(path)
    if path.exists() and any(path.iterdir()):
        raise FileExistsError(f"Target directory not empty: {path}")
    ensure_dir(path)
    (path / "apps").mkdir()
    (path / SWAT_PLUGINS_DIRNAME).mkdir()
    (path / "tests").mkdir()
    (path / "README.md").write_text(f"# {name}\n\nGenerated by swatctl.\n", encoding="utf-8")
    tmp = git_clone(swat_repo, ref=version)
    lib_src = tmp / SWAT_LIB_DIRNAME
    dest_lib = path / SWAT_LIB_DIRNAME
    if lib_src.exists():
        safe_copytree(lib_src, dest_lib, overwrite=False)
    else:
        # fallback: copy entire repo into lib/
        safe_copytree(tmp, dest_lib, overwrite=False)
    example_app = path / "apps" / "demo"
    ensure_dir(example_app)
    write_file(example_app / "index.html", TEMPLATES["index.html"].substitute(title=f"{name} demo", libdir=SWAT_LIB_DIRNAME, name="app"), overwrite=True)
    write_file(example_app / "app.js", TEMPLATES["page.js"].substitute(name="app", title=f"{name} demo"), overwrite=True)
    cfg = {"swat_repo": swat_repo, "swat_ref": version or "HEAD"}
    (path / "swatctl.json").write_text(json.dumps(cfg, indent=2), encoding="utf-8")
    shutil.rmtree(tmp, ignore_errors=True)
    return True

def set_swat_version(project_root: Path, swat_repo: str, ref: str, backup: bool = True):
    root = Path(project_root)
    lib_dir = root / SWAT_LIB_DIRNAME
    tmp = git_clone(swat_repo, ref=ref)
    src_lib = tmp / SWAT_LIB_DIRNAME
    if not src_lib.exists():
        raise FileNotFoundError("swat repo did not contain lib/ at root")
    if backup and lib_dir.exists():
        bak = root / (SWAT_LIB_DIRNAME + ".bak")
        if bak.exists():
            shutil.rmtree(bak)
        shutil.move(str(lib_dir), str(bak))
    safe_copytree(src_lib, lib_dir, overwrite=True)
    cfg = root / "swatctl.json"
    try:
        data = json.loads(cfg.read_text(encoding="utf-8")) if cfg.exists() else {}
    except Exception:
        data = {}
    data.update({"swat_repo": swat_repo, "swat_ref": ref})
    cfg.write_text(json.dumps(data, indent=2), encoding="utf-8")
    shutil.rmtree(tmp, ignore_errors=True)
    return True

def plugin_install(project_root: Path, plugin_repo: str, ref: str | None = None, plugin_subpath: str | None = None, overwrite: bool = False):
    root = Path(project_root)
    plugins_dir = root / SWAT_PLUGINS_DIRNAME
    ensure_dir(plugins_dir)
    tmp = git_clone(plugin_repo, ref=ref)
    candidates = []
    if plugin_subpath:
        p = tmp / plugin_subpath
        if p.exists():
            candidates.append(p)
    for nm in ("plugin.js", "index.js", "main.js"):
        p = tmp / nm
        if p.exists():
            candidates.append(p)
    p = tmp / "plugins"
    if p.exists() and p.is_dir():
        candidates.append(p)
    if not candidates:
        for f in tmp.iterdir():
            if f.suffix == ".js":
                candidates.append(f)
    if not candidates:
        shutil.rmtree(tmp, ignore_errors=True)
        raise FileNotFoundError("No plugin files found in the repo (tried plugin.js, index.js, plugins/). Use plugin_subpath to specify.")
    repo_name = Path(plugin_repo).stem
    dest = plugins_dir / repo_name
    if dest.exists():
        if not overwrite:
            raise FileExistsError(f"Plugin destination exists: {dest} (use overwrite=True)")
        shutil.rmtree(dest)
    dest.mkdir(parents=True)
    for c in candidates:
        target = dest / c.name
        if c.is_dir():
            shutil.copytree(c, target)
        else:
            shutil.copy2(c, target)
    meta = {"source": plugin_repo, "ref": ref or "HEAD"}
    (dest / "swat-plugin.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")
    shutil.rmtree(tmp, ignore_errors=True)
    return dest

def plugin_set_version(project_root: Path, plugin_name: str, ref: str):
    root = Path(project_root)
    plugins_dir = root / SWAT_PLUGINS_DIRNAME
    dest = plugins_dir / plugin_name
    if not dest.exists():
        raise FileNotFoundError("Plugin not installed: " + str(dest))
    meta_file = dest / "swat-plugin.json"
    if not meta_file.exists():
        raise FileNotFoundError("Plugin metadata missing (swat-plugin.json).")
    meta = json.loads(meta_file.read_text(encoding="utf-8"))
    repo = meta.get("source")
    if not repo:
        raise ValueError("Plugin metadata does not include source repo.")
    shutil.rmtree(dest)
    return plugin_install(project_root, repo, ref=ref, plugin_subpath=None, overwrite=True)

def show_info(project_root: Path):
    root = Path(project_root)
    info = {"project": str(root)}
    cfg = root / "swatctl.json"
    if cfg.exists():
        info["swatctl.json"] = json.loads(cfg.read_text(encoding="utf-8"))
    libdir = root / SWAT_LIB_DIRNAME
    info["lib_exists"] = libdir.exists()
    plugins = root / SWAT_PLUGINS_DIRNAME
    info["plugins"] = [p.name for p in plugins.iterdir()] if plugins.exists() else []
    apps = root / "apps"
    info["apps"] = [p.name for p in apps.iterdir()] if apps.exists() else []
    return info

def create_page(project_root: Path, pagename: str, title: str, overwrite: bool = False):
    root = Path(project_root)
    apps_dir = root / "apps"
    ensure_dir(apps_dir)
    page_dir = apps_dir / pagename
    if page_dir.exists() and not overwrite:
        raise FileExistsError(f"Page directory exists: {page_dir}")
    ensure_dir(page_dir)
    libdir_name = SWAT_LIB_DIRNAME
    write_file(page_dir / "index.html", TEMPLATES["index.html"].substitute(title=title, libdir=libdir_name, name=pagename), overwrite=overwrite)
    write_file(page_dir / f"{pagename}.js", TEMPLATES["page.js"].substitute(name=pagename, title=title), overwrite=overwrite)
    write_file(page_dir / f"{pagename}.css", TEMPLATES["page.css"].substitute(name=pagename), overwrite=overwrite)
    return page_dir